DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION(
	id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT,
    amount float,
    type VARCHAR(250) NOT NULL,
    date DATETIME,
    status VARCHAR(250) NOT NULL
);