pipeline {

  stages {
    stage("Maven Build") {
       steps {
          mvn clean package ./target/zuul-gateway-proxy-server-1.0.0.jar zuul-gateway-proxy-server-1.0.0.jar
       }
   }
   stage("Sonar Analysis") {
       steps {
       
       }
   }
   stage("Build Container Image") {
       steps {
       
       }
   }
   stage("Build Openshift deployment Image") {
       steps {
       	
       }
   }
   stage("publish to uDeploy") {
       steps {
       	
       }
   }
   stage("Deploy to DEV") {
       steps {
       	
       }
   }
   stage("Deploy to SIT") {
       steps {
       	
       }
   }
   stage("Automation Tests") {
       steps {
       	
       }
   }
   stage("Deploy to UAT") {
       steps {
       	
       }
   }
   stage("Deploy to PTE") {
       steps {
       	
       }
   }
   stage("Deploy to CTE") {
       steps {
       	
       }
   }
   stage("Deploy to PROD") {
       steps {
       	
       }
   }
   stage("Deploy to COB") {
       steps {
       	
       }
   }
 }
}