spring:
  application:
    name: gateway-proxy
  zipkin:
    enabled: true
    service.name: gateway-proxy
    sender.type: web
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

server:
  port: 8762
   
eureka:
  client:
    service-url:
      default-one: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
    fetch-registry: true
    register-with-eureka: false
#zuul:
  #routes:
   #accounts-service: 
      #service-id: accounts-service
      #path: /accounts/**
    #transaction-service: 
      #service-id: transaction-service
      #path: /transaction/**
zuul:
  sensitiveHeaders: Cookie,Set-Cookie